### ISSUE TITLE
Compiling cores with buildroot

### ISSUE THREAD

**Issue by paradadf** [libretro/yabause#116] opened 2019-09-02 22:45 UTC
Hi! I'm trying to add this three cores on recalbox. I've succesfully added yabause and yabasanshiro on pc (both x86 and x86_64), but I just can't sort out what's wrong with kronos.

* Kronos x86 error log: https://pastebin.com/xBjLFwJy
* Kronos x86_64 error log: https://pastebin.com/92eykKqG

I've also tried to build yabasanshiro on the xu4 too (is that the recommended core for xu4?), but it also fails.

* Yabasanshiro xu4 error log: https://pastebin.com/k9CnBMcj

Any assistance it very much appreciated.

**Comment by barbudreadmon** [comment] 2019-09-03 05:51
Kronos => it seems the recalbox GL headers are missing some stuff, i added your 2 missing defs in the project's defs (https://github.com/libretro/yabause/commit/b5fbe1d813d36226cae9c0a1513ba6077bc8ce4a) but imho you should consider updating recalbox's GL headers.

Yabasanshiro => use the "odroid-xu4" platform in the makefile.

Closing, re-open it if there are still missing defs issues (imho, you should just update your distro's headers though).

**Closed by barbudreadmon** 2019-09-03 05:51 UTC

**Comment by barbudreadmon** [comment] 2019-09-03 05:57
Actually there is no "odroid-xu4" platform, it's supposed to auto-detect platform once "odroid" is set as platform, but i guess it won't work for cross-compiling.
Maybe try forcing the detection with the following make command ?
```
make platform=odroid BOARD=ODROID-XU4
```

**Comment by bkg2k** [comment] 2019-09-03 11:23
GL Headers used in current/next recalbox releases (6.0/6.1) are provided by Mesa 3D 17.3.6 (Feb. 2018).
Not the latest, but not outdated though.
Does Kronos require newest headers? Or maybe the Mesa3D GL headers are missing some definitions?

**Comment by barbudreadmon** [comment] 2019-09-03 12:04
Defs like `GL_SHADER_STORAGE_BARRIER_BIT` exist since OpenGL 4.3 (2012), not sure why they aren't in mesa's headers from 2018 ? Maybe you should replace your headers by official GL/GLES headers ? https://github.com/KhronosGroup/OpenGL-Registry/tree/master/api

Anyway, https://github.com/libretro/yabause/commit/b5fbe1d813d36226cae9c0a1513ba6077bc8ce4a will provide those defs if they are missing from your headers.

**Comment by barbudreadmon** [comment] 2019-09-03 14:10
@bkg2k i can confirm those defs were added to mesa headers in 2012 : https://gitlab.freedesktop.org/mesa/mesa/commit/92b614172f750f93f218cd78a9f3c066c3629cab

**Comment by paradadf** [comment] 2019-09-03 18:38
@barbudreadmon thanks for the help. Building yabasanshiro with `make platform=odroid BOARD=ODROID-XU4` still fails.
https://pastebin.com/HnZ8YZnQ

**Comment by barbudreadmon** [comment] 2019-09-03 19:18
@paradadf Remove `"`, you are using `platform="odroid BOARD=ODROID-XU4"` instead of `platform=odroid BOARD=ODROID-XU4`

NB : `FORCE_GLES=1` is also useless if you are already building with `platform=odroid BOARD=ODROID-XU4`

**Comment by paradadf** [comment] 2019-09-03 19:28
Ups! Thank you! 
We still need to `FORCE_GLES=1` because we don't build retroarch with opengl support atm.

**Comment by barbudreadmon** [comment] 2019-09-03 19:29
> We still need to FORCE_GLES=1 because we don't build retroarch with opengl support atm.

No you don't, what i mean is that `platform=odroid BOARD=ODROID-XU4` is already forcing gles

**Comment by paradadf** [comment] 2019-09-03 19:31
I mean for x86(_64). If I don't force gles there, it doesn't work.

**Comment by barbudreadmon** [comment] 2019-09-03 19:34
Oh, ok... i guess that explains the issue with the missing Kronos headers. You can remove Kronos from your distro then, it won't run with gles. Honestly not using OpenGL on desktop is a major issue, many cores just won't run as well or won't run at all without OpenGL.

**Comment by paradadf** [comment] 2019-09-03 19:42
We will work on it after recalbox 6.1 is released. Thanks for the heads up!
