### ISSUE TITLE
Yabause saturn libretro core , crash

### ISSUE THREAD

**Issue by nandobyker** [libretro/yabause#41] opened 2017-12-28 14:18 UTC
Im running windows 10 PRO v 1709 OS BUILD 1629.125

i try to load yabause v0.9.14 c55eef9

I have the saturn_bios.bin in the system folder  rom folder  is a Nin/Cue File 
But when i load the rom  it only show a black screen with save state then it freeze

any help for this
thanks

**Comment by raelgc** [comment] 2017-12-28 16:50
Are you trying to load a save state or it helps every game startup?

**Comment by nandobyker** [comment] 2017-12-28 16:53
it show in every game startup  whithout doing it , it show automatically and then crash

**Comment by ofry** [comment] 2019-07-15 14:18
@nandobyker Is it fixed now?

**Comment by mrcmunir** [comment] 2019-08-06 08:30
In aarch64 linux i can confirm unstable now compared in the past with 2.3.0/2.4.0 core!?

I need force_gles for runing in Nvidia jetson nanno not working in OpenGL context.
I can't debug to much because the trace are corrupt.

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000007fb3df105c in RBGGenerator_update ()
   from /opt/retroarena/libretrocores/yabasanshiro_libretro.so
#2  0x0000007fb3d68084 in Vdp2DrawRotation_in ()
   from /opt/retroarena/libretrocores/yabasanshiro_libretro.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Any ideas? What cause this? and apparently it is a problem in the libretro core  since the yabause sanshiro Qt native version works correctly there.

It does not happen with all the games only with some (Croc, panzer dragon after the menu).

but formerly it worked I will have to look where it breaks but that will take some time.


but formerly it worked I will have to look where it breaks but that will take some time.

**Comment by barbudreadmon** [comment] 2019-08-06 12:12
From what i can tell, it's shocking on compute shaders (introduced in 2.5.0), so you should disable them in core options (i guess i'll have to disable them by default).

To run the core with opengl context, you need to build RA with opengl enabled and opengles disabled, maybe with opengl context the compute shaders would work ?

Anyway, closing, in the first place you shouldn't bump old issues with unrelated other issues (seriously : other core + other platform...), and i consider the original issue to be solved (no answer from OP, and i'm pretty sure it was related to the threading stuff i fixed some weeks ago)

**Closed by barbudreadmon** 2019-08-06 12:12 UTC

**Comment by mrcmunir** [comment] 2019-08-06 13:39
> From what i can tell, it's shoking on compute shaders (introduced in 2.5.0), so you should disable them in core options (i guess i'll have to disable them by default).
> 
> To run the core with opengl context, you need to build RA with opengl enabled and opengles disabled (you can't support both with the same RA build), maybe with opengl context the compute shaders would work ?
> 
> Anyway, closing, in the first place you shouldn't bump old issues with unrelated other issues (seriously : other core + other platform...), and i consider the original issue to be solved (no answer from OP, and i'm pretty sure it was related to the threading stuff i fixed some weeks ago)

Ops I didn't see the date sorry 
Thanks you suggestions that Disabling retroarch opengl es working in Context OpenGL now :)
Seems this computer shader broken on OpenGL ES but working partially with OpenGL desktop (in standalone has some bugs graphics with ON but no crash)

Soo maybe neded select Option beucase not very stable in OpenGL desktop broken graphics in severals games.
![Screenshot from 2019-08-06 15-21-48](https://user-images.githubusercontent.com/1274014/62544224-afa8f400-b85f-11e9-964c-ffa2062ff4f9.png)
