### ISSUE TITLE
Slower than standalone yabause

### ISSUE THREAD

**Issue by mac1202** [libretro/yabause#6] opened 2014-08-15 21:48 UTC
hello trying to play shining the holy ark the game run really slow on retroarch. Playing on standalone yabause with the same bios and setting ( software renderer, frameskip enable) the game run faster.

**Comment by barbudreadmon** [comment] 2019-08-26 09:15
Cleaning up, i consider this as a duplicate of https://github.com/libretro/yabause/issues/51.

On a sidenote : 
- there is an overhead when using libretro vs standalone, so i don't expect a 1:1 conversion of a standalone emulator to run as fast.
- i think multi-thread was broken when this issue was opened, it was fixed since then.
- there are now 2 other yabause-based cores which might perform better, they require a decent gpu though.

Anyway, closing !

**Closed by barbudreadmon** 2019-08-26 09:15 UTC
