### ISSUE TITLE
[Kronos] CHD - Font rendering

### ISSUE THREAD

**Issue by Dogway** [libretro/yabause#125] opened 2019-10-07 15:13 UTC
In CHD compressed format some games render fonts as garbage. I found this on Burning Rangers in the first BIOS screen footnote -Sega Enterprises, Ltd....- but also on Panzer Dragoon FMV subtitles. Other Panzer Dragoon games are fine, or if I use bin/cue format.

**Comment by barbudreadmon** [comment] 2019-10-11 18:19
I'm unable to reproduce any of those issues, i'll need more information : 
- bios version
- gpu
- options
- game version

**Comment by Dogway** [comment] 2019-10-11 19:42
_Retroarch 1.7.7 x64
Win7 SP1 x64
i7-4790K, 4x4Gb
GTX 1070 (436.15)_

Kronos build from 30/08 (onwards?)
saturn_bios.bin af5828fdff51384f99b3c4926be27762 (recommended in docs)

Happens on the Panzer Dragoon FMV AFTER the title screen, not the one before.
Runahead, rewind and cheevos disabled.

```
kronos_addon_cart = "none"
kronos_addon_cartridge = "auto"
kronos_auto_select_cart = "enabled"
kronos_filter_mode = "none"
kronos_force_hle_bios = "disabled"
kronos_meshmode = "enabled"
kronos_multitap_port1 = "disabled"
kronos_multitap_port2 = "disabled"
kronos_opengl_version = "4.5"
kronos_polygon_mode = "perspective_correction"
kronos_resolution_mode = "1080p"
kronos_scanlines = "disabled"
kronos_service_enabled = "disabled"
kronos_sh2coretype = "kronos"
kronos_upscale_mode = "none"
kronos_use_beetle_saves = "enabled"
kronos_use_cs = "disabled"
kronos_videocoretype = "opengl_cs"
kronos_videoformattype = "NTSC"
```

It fixes if I set kronos_videoformattype to PAL, despite the game being the USA version.

**Comment by barbudreadmon** [comment] 2019-10-12 08:46
It seems to be fixed by https://github.com/libretro/yabause/commit/2995a5f9ab63a87c097ea677f233c421950bded7, please confirm.

**Comment by Dogway** [comment] 2019-10-16 00:16
Sorry, I couldn't find a Windows build in the buildbot

**Comment by barbudreadmon** [comment] 2019-10-16 03:27
Maybe it's time to get some glasses then ? It built successfully 4 days ago : http://buildbot.libretro.com/nightly/windows/x86_64/latest/kronos_libretro.dll.zip

I'll close, reopen if the issue persist.

**Closed by barbudreadmon** 2019-10-16 03:27 UTC

**Comment by Dogway** [comment] 2019-10-16 03:34
Tone down a notch. It wasn't merged in master branch so I searched on your usual PR buildbots:
https://travis-ci.org/Yabause/yabause/branches
https://ci.appveyor.com/project/Guillaumito/yabause/history

Good luck with community reports.

**Comment by barbudreadmon** [comment] 2019-10-16 03:46
Oh, so you say it's not on the buildbot while you are looking somewhere else, and you get mad when someone tease you about it. Nice.
