### ISSUE TITLE
[question] Multi-Tap

### ISSUE THREAD

**Issue by DisneyFanatic4** [libretro/yabause#178] opened 2020-02-20 02:54 UTC
Have you successfully enabled both multi-tap options and configured 10 controllers in the emulator?  When I enable the second multi-tap the emulator speeds up and the game menu's progress at 500% speed.  I'm trying to get Sega Bomberman to work with 10 players.

**Comment by barbudreadmon** [comment] 2020-02-20 09:22
in all 3 yabause-based cores ? i don't remember seeing this behavior in kronos (which is the only one i'm using), i know there are other issues with dual multitap though (buttons acting as "autofire").

**Comment by DisneyFanatic4** [comment] 2020-02-21 02:50
I'm using the libretro core within RetroPie.  I believe what I'm experiencing is the "autofire" buttons you mention.  When it loads the main game menu screen, any button press will fire multiple times causing rapid selection through the initial menu and render unplayable.

**Comment by barbudreadmon** [comment] 2020-02-21 09:04
Ok, this issue is known upstream, so i'll close this one as duplicate.
The only known workaround atm would be to use beetle/mednafen.

**Closed by barbudreadmon** 2020-02-21 09:04 UTC

**Comment by DisneyFanatic4** [comment] 2020-02-24 00:54
Thanks for the feedback.  Would you happen to know which codebase this is known in upstream and is it being tracked?

**Comment by barbudreadmon** [comment] 2020-02-24 06:46
I only know of the kronos one : https://github.com/FCare/Kronos/issues/367 (sorry, it's in french)
I guess the 2 other codebase might have issues opened about this, since the issue is common and has been known since yabause.
