### ISSUE TITLE
controller have not answer ?

### ISSUE THREAD

**Issue by PowaBanga** [libretro/yabause#44] opened 2018-04-16 17:02 UTC
hi all,
I am tryng to use bomberman with yabause (european version in my cas)
But when the game ask to me to push on start to continue, nothing happens

My controler works really good on psx-r and Snes cores
I am on archlinux, and I had same compil yabause from this git, but this didn't fix that...

somebody can help me please ?

**Comment by barbudreadmon** [comment] 2019-08-26 10:10
I can't reproduce your issue, however i know there are some problems in yabause-based cores when 2 multitaps are enabled, is that your case ?

**Comment by barbudreadmon** [comment] 2019-09-14 09:49
No answer, closing

**Closed by barbudreadmon** 2019-09-14 09:49 UTC
