### ISSUE TITLE
Sound bug / Hangs

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/yabause#22] opened 2015-09-23 12:33 UTC
Some differences with Yabause 0.9.14 stand-alone on win64:

-Advanced VG: the starting sound repeats over and over, game can hang after the match digit voices.

-Dragon Ball Z Shinbutoden: game just hangs after you selected you character and the CPU does its digit voice, not playable at all.

None of this occurs in stand-alone.

Messages like this in the log:

RetroArch [INFO] :: Average audio buffer saturation: 13.60 %, standard deviation (percentage points): 16.55 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 77.50 %. Close to blocking: 0.00 %.

**Comment by twinaphex** [comment] 2015-09-23 14:31
It using the interpreter CPU core still and the software renderer, standalone likely doesn't.

**Comment by Tatsuya79** [comment] 2015-09-23 15:07
I just checked standalone, it's on software renderer and SH2 Interpreter.

**Comment by rcaridade145** [comment] 2016-11-30 14:33
Looking at current Makefile from libretro https://github.com/libretro/yabause/blob/master/libretro/Makefile#L232  and for instance how it is defined on Yabause https://github.com/Yabause/yabause/blob/master/yabause/src/CMakeLists.txt#L82 Libretro seems to be using by default the new implementation which is optional on the standalone build.

**Comment by barbudreadmon** [comment] 2019-08-26 09:54
The issue is still happening, i'm thinking of rebasing current core against current standalone since i would expect the issue is coming from some half-assed backport.

**Comment by barbudreadmon** [comment] 2019-08-27 12:38
i rebased the yabause libretro core against latest standalone version (and using the same compilation options), no more sound issues for those games. Closing.

**Closed by barbudreadmon** 2019-08-27 12:38 UTC
